server:
  host: 0.0.0.0
  port: 9000
  apiKey: ""
discordBots:
  - uniqueId: bot1
    discordToken: 
    discordAppId: 
    discordChannelId: 
    discordSessionId: 
    discordGuildId: 
    upscaleCount:
